REMEMBERIZER_ENDPOINT = "https://api.rememberizer.ai/api/v1"
REMEMBERIZER_SEARCH_ENDPOINT = f"{REMEMBERIZER_ENDPOINT}/documents/search/"
REMEMBERIZER_ACCOUNT_ENDPOINT = f"{REMEMBERIZER_ENDPOINT}/account/"
REMEMBERIZER_SLACK_INTEGRATIONS_ENDPOINT = (
    f"{REMEMBERIZER_ENDPOINT}/documents?integration_type=slack"
)
REMEMBERIZER_DISCUSSION_CONTENT_ENDPOINT = (
    f"{REMEMBERIZER_ENDPOINT}/discussions/{{}}/contents?integration_type=slack"
)
